services:
  formula-app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      - ./index.html:/app/index.html
      - ./tailwind.config.js:/app/tailwind.config.js
      - ./postcss.config.js:/app/postcss.config.js
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - npm_network
networks:
  npm_network:
    external: true