# docker-compose.yml
services:
  formula-app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      - ./index.html:/app/index.html
      - ./vite.config.ts:/app/vite.config.ts
      - ./tsconfig.json:/app/tsconfig.json
      # Note: No tsconfig.app.json mounting, since we don't need it
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - npm_network
networks:
  npm_network:
    external: true